### ISSUE TITLE
Cannot access to balancedtest.csv and fulltrain.csv file

### ISSUE THREAD

**Issue by P17seongbin** [BUPT-GAMMA/CompareNet_FakeNewsDetection#1]
Hello, I'm P17seongbin. 

I had been inspired by your paper _Compare to The Knowledge: Graph Neural Fake News Detection with External Knowledge_
 and try to reproduce the performance of CompareNet.

**Problem:**
However, train and test data named balancedtest.csv and fulltrain.csv file is inaccessable via the link. (maybe broken?)
the link: https://homes.cs.washington.edu/~hrashkin/fact_checking_files/newsfiles.tar.gz

thanks for check this issue. have a nice day.

**Comment by ytc272098215** [comment]
Fixed. Thanks for your interest.

**Comment by Gjt20021214** [comment]
我想请问这两个文件在哪？好像没有找到，但是代码需要这两个csv文件

**Comment by Gjt20021214** [comment]
已经找到了
